# Auto-generated by AQ-Editor-Prune.ps1 at 20250923_162539
# This plan MOVES candidate files into: C:\Users\Steph\Dev\aq30-unity\Backups\Pruned\20250923_162539
# Review the list before running. Usage:
#   pwsh -NoProfile -ExecutionPolicy Bypass "C:\Users\Steph\Dev\aq30-unity\Tools\Reports\editor_prune_plan_20250923_162539.ps1" [-WhatIf]
param([switch])
$dest = "C:\Users\Steph\Dev\aq30-unity\Backups\Pruned\20250923_162539"
if(-not (Test-Path $dest)) { New-Item -ItemType Directory -Path $dest | Out-Null }
